version: '3'

tasks:
  build:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake ..
      - cmake --build .

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake ..
      - cmake --build .
      - ./TradeRiskTrackerTests
